version: '3.8'
services:
  app:
    container_name: spst-container
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: "spst-kniznica"
      DATABASE_USER: "root"
      DATABASE_PASS: "PETERdinis1234"
      DATABASE_URI: "mongodb://myUser:myPassword@localhost:27017/spst-kniznica"
    ports:
      - '4000:4000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - docker.env